// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBF8D4pG76RObOTVPVdxxe-eabNgHv8CjQ',
    appId: '1:486058582422:web:4b4ec84002659cb1a17db7',
    messagingSenderId: '486058582422',
    projectId: 'drug-app-8c92b',
    authDomain: 'drug-app-8c92b.firebaseapp.com',
    storageBucket: 'drug-app-8c92b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsLvpyejeJSR-WjZVUx-uoAP785WHVzCw',
    appId: '1:486058582422:android:e4a3671744338ddaa17db7',
    messagingSenderId: '486058582422',
    projectId: 'drug-app-8c92b',
    storageBucket: 'drug-app-8c92b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBq_UagBRD2IS1v8zA95L9OKY8kO1UiB_Q',
    appId: '1:486058582422:ios:8de1ed1c3bea8c6fa17db7',
    messagingSenderId: '486058582422',
    projectId: 'drug-app-8c92b',
    storageBucket: 'drug-app-8c92b.firebasestorage.app',
    iosBundleId: 'com.example.drugApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBq_UagBRD2IS1v8zA95L9OKY8kO1UiB_Q',
    appId: '1:486058582422:ios:8de1ed1c3bea8c6fa17db7',
    messagingSenderId: '486058582422',
    projectId: 'drug-app-8c92b',
    storageBucket: 'drug-app-8c92b.firebasestorage.app',
    iosBundleId: 'com.example.drugApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBF8D4pG76RObOTVPVdxxe-eabNgHv8CjQ',
    appId: '1:486058582422:web:e821c1753ec372bba17db7',
    messagingSenderId: '486058582422',
    projectId: 'drug-app-8c92b',
    authDomain: 'drug-app-8c92b.firebaseapp.com',
    storageBucket: 'drug-app-8c92b.firebasestorage.app',
  );
}
